language: generic

env:
  - R_LIBS_USER=~/R

cache:
  directories:
    - node_modules
    - ~/R

addons:
  apt:
    sources:
      - sourceline: 'deb https://deb.nodesource.com/node_8.x trusty main'
      - sourceline: 'deb https://cran.rstudio.com/bin/linux/ubuntu trusty/'
    packages:
      - nodejs
      - python3
      - python3-dev
      - python3-pip
      - r-base
      - r-base-dev

before_install:
  - npm install stencila/node
  - pip install --user https://github.com/stencila/py/archive/master.zip
  - Rscript -e "devtools::install_github('stencila/r')"

install:
  - make setup

script:
  - make test
